### ISSUE TITLE
Resource Aliases

### ISSUE THREAD

**Issue by grep-ir** [covermymeds/azure-key-vault-agent#56]
Azure has specific limitations on what resources can be named.  It would be nice if we could create our own locally significant aliases for resources and be able to reference them in templates.

```
    resources:
      - kind: secret
        name: pem-test
        alias: mycert
        vaultBaseURL: https://cjohnson-kv.vault.azure.net/

    sinks:
        - path: ./mycert.key
          template: '{{ privateKey "mycert" }}'
        - path: ./mycert.cert
          template: '{{ cert "mycert" }}'
        - path: ./mycert-metadata.json
          template: '{{ index .Certs "mycert" | toJson }}'
```
