### ISSUE TITLE
Querying the same secret present in multiple vaults will only return the value from the last worker

### ISSUE THREAD

**Issue by Serneum** [covermymeds/azure-key-vault-agent#78]
Examples:

```yaml
workers:
  -
    resources:
      - kind: all-secrets
        vaultBaseURL: https://vault1-tst.vault.azure.net/
        credential: cred1
      - kind: secret
        name: secret-key-base
        vaultBaseURL: https://vault2-tst.vault.azure.net/
        credential: cred2

    sinks:
      - path: secrets.json
        template: '{{ (index .Secrets "secret-key-base").Value }}'
    frequency: 60s
```

```yaml
workers:
  -
    resources:
      - kind: secret
        name: secret-key-base
        vaultBaseURL: https://vault1-tst.vault.azure.net/
        credential: cred1
      - kind: secret
        name: secret-key-base
        vaultBaseURL: https://vault2-tst.vault.azure.net/
        credential: cred2

    sinks:
      - path: secrets.json
        template: '{{ (index .Secrets "secret-key-base").Value }}'
    frequency: 60s
```

The value set in the `Secrets` map will always be whichever worker ran most recently. Maybe this okay, but maybe an error should be thrown instead. We could likely check if a secret is present as each one is returned. For `all-secrets`, that will either be after we determine the secret name, or maybe after returning the full map, then iterating over all keys and checking before assigning the data to the Secrets map
