### ISSUE TITLE
Resource with hyphen (-) is giving error invalid memory address or nil pointer 

### ISSUE THREAD

**Issue by ashwanisharmamw** [covermymeds/azure-key-vault-agent#89]
I have secrets name with Hyphen in the name and i tired to pull these using index  and getting nil pointer error 

workers:
  -
      resources:
      - kind: secret
      name: pem-test
      vaultBaseURL: https://test-key-vault.vault.azure.net/
      sinks:
      - path: ./test.secret
      template: '{{ index .Secrets "pem-test.Value" }}'

**Comment by ashwanisharmamw** [comment]
@vickicello - Can you please help on this issue

**Comment by vickicello** [comment]
@ashwanisharmamw The `.Value` syntax unfortunately does not work on secret names that have special characters (like hyphens). One easy workaround is to create an alias for your secret name like this:

```
  resources:
  - kind: secret
    name: pem-test
    alias: pemtest
    vaultBaseURL: https://test-key-vault.vault.azure.net/
  sinks:
  - path: ./test.secret
    template: '{{ index .Secrets.pemtest.Value }}'
```

Hopefully using an alias will work for you.
